<?php

declare (strict_types=1);
namespace Doctrine\Common\Proxy;

use function class_exists;
use Doctrine\Common\Proxy\Exception\InvalidArgumentException;
use Doctrine\Common\Proxy\Exception\OutOfBoundsException;
use Doctrine\Common\Util\Class_Utils;
use Doctrine\Persistence\Mapping\Class_Metadata;
use Doctrine\Persistence\Mapping\Class_Metadata_Factory;
use function file_exists;
use function filemtime;
use function in_array;
/**
 * Abstract factory for proxy objects.
 *
 * @deprecated The AbstractProxyFactory class is deprecated since doctrine/common 3.5.
 */
abstract class Abstract_Proxy_Factory
{
    /**
     * Never autogenerate a proxy and rely that it was generated by some
     * process before deployment.
     */
    public const AUTOGENERATE_NEVER = 0;
    /**
     * Always generates a new proxy in every request.
     *
     * This is only sane during development.
     */
    public const AUTOGENERATE_ALWAYS = 1;
    /**
     * Autogenerate the proxy class when the proxy file does not exist.
     *
     * This strategy causes a file_exists() call whenever any proxy is used the
     * first time in a request.
     */
    public const AUTOGENERATE_FILE_NOT_EXISTS = 2;
    /**
     * Generate the proxy classes using eval().
     *
     * This strategy is only sane for development, and even then it gives me
     * the creeps a little.
     */
    public const AUTOGENERATE_EVAL = 3;
    /**
     * Autogenerate the proxy class when the proxy file does not exist or
     * when the proxied file changed.
     *
     * This strategy causes a file_exists() call whenever any proxy is used the
     * first time in a request. When the proxied file is changed, the proxy will
     * be updated.
     */
    public const AUTOGENERATE_FILE_NOT_EXISTS_OR_CHANGED = 4;
    private const AUTOGENERATE_MODES = [self::AUTOGENERATE_NEVER, self::AUTOGENERATE_ALWAYS, self::AUTOGENERATE_FILE_NOT_EXISTS, self::AUTOGENERATE_EVAL, self::AUTOGENERATE_FILE_NOT_EXISTS_OR_CHANGED];
    /** @var ClassMetadataFactory */
    private $metadata_factory;
    /** @var ProxyGenerator the proxy generator responsible for creating the proxy classes/files. */
    private $proxy_generator;
    /** @var int Whether to automatically (re)generate proxy classes. */
    private $auto_generate;
    /** @var ProxyDefinition[] */
    private $definitions = [];
    /**
     * @param bool|int $autoGenerate
     *
     * @throws InvalidArgumentException When auto generate mode is not valid.
     */
    public function __construct(Proxy_Generator $proxy_generator, Class_Metadata_Factory $metadata_factory, $auto_generate)
    {
        $this->proxy_generator = $proxy_generator;
        $this->metadata_factory = $metadata_factory;
        $this->auto_generate = (int) $auto_generate;
        if (!in_array($this->auto_generate, self::AUTOGENERATE_MODES, true)) {
            throw InvalidArgumentException::invalid_auto_generate_mode($auto_generate);
        }
    }
    /**
     * Gets a reference proxy instance for the entity of the given type and identified by
     * the given identifier.
     *
     * @param  string       $className
     * @param  array<mixed> $identifier
     *
     * @return Proxy
     *
     * @throws OutOfBoundsException
     */
    public function get_proxy($class_name, array $identifier)
    {
        $definition = $this->definitions[$class_name] ?? $this->get_proxy_definition($class_name);
        $fqcn = $definition->proxy_class_name;
        $proxy = new $fqcn($definition->initializer, $definition->cloner);
        foreach ($definition->identifier_fields as $id_field) {
            if (!isset($identifier[$id_field])) {
                throw OutOfBoundsException::missing_primary_key_value($class_name, $id_field);
            }
            $definition->reflection_fields[$id_field]->set_value($proxy, $identifier[$id_field]);
        }
        return $proxy;
    }
    /**
     * Generates proxy classes for all given classes.
     *
     * @param ClassMetadata[] $classes  The classes (ClassMetadata instances)
     *  for which to generate proxies.
     * @param string          $proxyDir The target directory of the proxy classes. If not specified, the
     *                                  directory configured on the Configuration of the EntityManager used
     *                                  by this factory is used.
     *
     * @return int Number of generated proxies.
     */
    public function generate_proxy_classes(array $classes, $proxy_dir = null)
    {
        $generated = 0;
        foreach ($classes as $class) {
            if ($this->skip_class($class)) {
                continue;
            }
            $proxy_file_name = $this->proxy_generator->get_proxy_file_name($class->get_name(), $proxy_dir);
            $this->proxy_generator->generate_proxy_class($class, $proxy_file_name);
            $generated += 1;
        }
        return $generated;
    }
    /**
     * Reset initialization/cloning logic for an un-initialized proxy
     *
     * @return Proxy
     *
     * @throws InvalidArgumentException
     */
    public function reset_uninitialized_proxy(Proxy $proxy)
    {
        if ($proxy->__is_initialized()) {
            throw InvalidArgumentException::unitialized_proxy_expected($proxy);
        }
        $class_name = Class_Utils::get_class($proxy);
        $definition = $this->definitions[$class_name] ?? $this->get_proxy_definition($class_name);
        $proxy->__set_initializer($definition->initializer);
        $proxy->__set_cloner($definition->cloner);
        return $proxy;
    }
    /**
     * Get a proxy definition for the given class name.
     *
     * @param string $className
     * @psalm-param class-string $className
     *
     * @return ProxyDefinition
     */
    private function get_proxy_definition($class_name)
    {
        $class_metadata = $this->metadata_factory->get_metadata_for($class_name);
        $class_name = $class_metadata->get_name();
        // aliases and case sensitivity
        $this->definitions[$class_name] = $this->create_proxy_definition($class_name);
        $proxy_class_name = $this->definitions[$class_name]->proxy_class_name;
        if (!class_exists($proxy_class_name, false)) {
            $file_name = $this->proxy_generator->get_proxy_file_name($class_name);
            switch ($this->auto_generate) {
                case self::AUTOGENERATE_NEVER:
                    require $file_name;
                    break;
                case self::AUTOGENERATE_FILE_NOT_EXISTS:
                    if (!file_exists($file_name)) {
                        $this->proxy_generator->generate_proxy_class($class_metadata, $file_name);
                    }
                    require $file_name;
                    break;
                case self::AUTOGENERATE_ALWAYS:
                    $this->proxy_generator->generate_proxy_class($class_metadata, $file_name);
                    require $file_name;
                    break;
                case self::AUTOGENERATE_EVAL:
                    $this->proxy_generator->generate_proxy_class($class_metadata, false);
                    break;
                case self::AUTOGENERATE_FILE_NOT_EXISTS_OR_CHANGED:
                    if (!file_exists($file_name) || filemtime($file_name) < filemtime($class_metadata->get_reflection_class()->get_file_name())) {
                        $this->proxy_generator->generate_proxy_class($class_metadata, $file_name);
                    }
                    require $file_name;
                    break;
            }
        }
        return $this->definitions[$class_name];
    }
    /**
     * Determine if this class should be skipped during proxy generation.
     *
     * @return bool
     */
    abstract protected function skip_class(Class_Metadata $metadata);
    /**
     * @param string $className
     * @psalm-param class-string $className
     *
     * @return ProxyDefinition
     */
    abstract protected function create_proxy_definition($class_name);
}