<?php

declare (strict_types=1);
namespace Doctrine\Common\Proxy;

use function array_combine;
use function array_diff;
use function array_key_exists;
use function array_map;
use function array_slice;
use function array_unique;
use function assert;
use Backed_Enum;
use function bin2hex;
use function call_user_func;
use function chmod;
use function class_exists;
use const DIRECTORY_SEPARATOR;
use function dirname;
use Doctrine\Common\Proxy\Exception\InvalidArgumentException;
use Doctrine\Common\Proxy\Exception\UnexpectedValueException;
use Doctrine\Common\Util\Class_Utils;
use Doctrine\Persistence\Mapping\Class_Metadata;
use function explode;
use function file;
use function file_put_contents;
use function get_class;
use function implode;
use function in_array;
use function interface_exists;
use function is_callable;
use function is_dir;
use function is_scalar;
use function is_string;
use function is_writable;
use function lcfirst;
use function ltrim;
use function method_exists;
use function mkdir;
use const PHP_VERSION_ID;
use function preg_match;
use function preg_match_all;
use function preg_replace;
use function preg_split;
use const PREG_SPLIT_DELIM_CAPTURE;
use function random_bytes;
use ReflectionIntersectionType;
use ReflectionMethod;
use ReflectionNamedType;
use ReflectionParameter;
use ReflectionProperty;
use Reflection_Type;
use ReflectionUnionType;
use function rename;
use function rtrim;
use function sprintf;
use function str_replace;
use function strpos;
use function strrev;
use function strtolower;
use function strtr;
use function substr;
use function trim;
use function var_export;
/**
 * This factory is used to generate proxy classes.
 * It builds proxies from given parameters, a template and class metadata.
 *
 * @deprecated The ProxyGenerator class is deprecated since doctrine/common 3.5.
 */
class Proxy_Generator
{
    /**
     * Used to match very simple id methods that don't need
     * to be decorated since the identifier is known.
     */
    public const PATTERN_MATCH_ID_METHOD = <<<'EOT'
    ((?(DEFINE)
      (?<type>\\?[a-z_\x7f-\xff][\w\x7f-\xff]*(?:\\[a-z_\x7f-\xff][\w\x7f-\xff]*)*)
      (?<intersection_type>(?&type)\s*&\s*(?&type))
      (?<union_type>(?:(?:\(\s*(?&intersection_type)\s*\))|(?&type))(?:\s*\|\s*(?:(?:\(\s*(?&intersection_type)\s*\))|(?&type)))+)
    )(?:public\s+)?(?:function\s+%s\s*\(\)\s*)\s*(?::\s*(?:(?&union_type)|(?&intersection_type)|(?:\??(?&type)))\s*)?{\s*return\s*\$this->%s;\s*})i
    EOT;
    /**
     * The namespace that contains all proxy classes.
     *
     * @var string
     */
    private $proxy_namespace;
    /**
     * The directory that contains all proxy classes.
     *
     * @var string
     */
    private $proxy_directory;
    /**
     * Map of callables used to fill in placeholders set in the template.
     *
     * @var string[]|callable[]
     */
    protected $placeholders = ['baseProxyInterface' => Proxy::class, 'additionalProperties' => ''];
    /**
     * Template used as a blueprint to generate proxies.
     *
     * @var string
     */
    protected $proxy_class_template = '<?php

namespace <namespace>;
<enumUseStatements>
/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE\'S PROXY GENERATOR
 */
class <proxyShortClassName> extends \<className> implements \<baseProxyInterface>
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = <lazyPropertiesNames>;

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = <lazyPropertiesDefaults>;

<additionalProperties>

<constructorImpl>

<magicGet>

<magicSet>

<magicIsset>

<sleepImpl>

<wakeupImpl>

<cloneImpl>

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, \'__load\', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    <methods>
}
';
    /**
     * Initializes a new instance of the <tt>ProxyFactory</tt> class that is
     * connected to the given <tt>EntityManager</tt>.
     *
     * @param string $proxyDirectory The directory to use for the proxy classes. It must exist.
     * @param string $proxyNamespace The namespace to use for the proxy classes.
     *
     * @throws InvalidArgumentException
     */
    public function __construct($proxy_directory, $proxy_namespace)
    {
        if (!$proxy_directory) {
            throw InvalidArgumentException::proxy_directory_required();
        }
        if (!$proxy_namespace) {
            throw InvalidArgumentException::proxy_namespace_required();
        }
        $this->proxy_directory = $proxy_directory;
        $this->proxy_namespace = $proxy_namespace;
    }
    /**
     * Sets a placeholder to be replaced in the template.
     *
     * @param string          $name
     * @param string|callable $placeholder
     *
     * @throws InvalidArgumentException
     */
    protected function set_placeholder($name, $placeholder): void
    {
        if (!is_string($placeholder) && !is_callable($placeholder)) {
            throw InvalidArgumentException::invalid_placeholder($name);
        }
        $this->placeholders[$name] = $placeholder;
    }
    /**
     * Sets the base template used to create proxy classes.
     *
     * @param string $proxyClassTemplate
     */
    public function set_proxy_class_template($proxy_class_template): void
    {
        $this->proxy_class_template = (string) $proxy_class_template;
    }
    /**
     * Generates a proxy class file.
     *
     * @param ClassMetadata $class    Metadata for the original class.
     * @param string|bool   $fileName Filename (full path) for the generated class. If none is given, eval() is used.
     *
     * @throws InvalidArgumentException
     * @throws UnexpectedValueException
     */
    public function generate_proxy_class(Class_Metadata $class, $file_name = false): void
    {
        $this->verify_class_can_be_proxied($class);
        preg_match_all('(<([a-zA-Z]+)>)', $this->proxy_class_template, $placeholder_matches);
        $placeholder_matches = array_combine($placeholder_matches[0], $placeholder_matches[1]);
        $placeholders = [];
        foreach ($placeholder_matches as $placeholder => $name) {
            $placeholders[$placeholder] = $this->placeholders[$name] ?? [$this, 'generate' . $name];
        }
        foreach ($placeholders as &$placeholder) {
            if (!is_callable($placeholder)) {
                continue;
            }
            $placeholder = call_user_func($placeholder, $class);
        }
        $proxy_code = strtr($this->proxy_class_template, $placeholders);
        if (!$file_name) {
            $proxy_class_name = $this->generate_namespace($class) . '\\' . $this->generate_proxy_short_class_name($class);
            if (!class_exists($proxy_class_name)) {
                eval(substr($proxy_code, 5));
            }
            return;
        }
        $parent_directory = dirname($file_name);
        if (!is_dir($parent_directory) && @mkdir($parent_directory, 0775, true) === false) {
            throw UnexpectedValueException::proxy_directory_not_writable($this->proxy_directory);
        }
        if (!is_writable($parent_directory)) {
            throw UnexpectedValueException::proxy_directory_not_writable($this->proxy_directory);
        }
        $tmp_file_name = $file_name . '.' . bin2hex(random_bytes(12));
        file_put_contents($tmp_file_name, $proxy_code);
        @chmod($tmp_file_name, 0664);
        rename($tmp_file_name, $file_name);
    }
    /** @throws InvalidArgumentException */
    private function verify_class_can_be_proxied(Class_Metadata $class): void
    {
        if ($class->get_reflection_class()->is_final()) {
            throw InvalidArgumentException::class_must_not_be_final($class->get_name());
        }
        if ($class->get_reflection_class()->is_abstract()) {
            throw InvalidArgumentException::class_must_not_be_abstract($class->get_name());
        }
        if (PHP_VERSION_ID >= 80200 && $class->get_reflection_class()->is_read_only()) {
            throw InvalidArgumentException::class_must_not_be_read_only($class->get_name());
        }
    }
    /**
     * Generates the proxy short class name to be used in the template.
     */
    private function generate_proxy_short_class_name(Class_Metadata $class): string
    {
        $proxy_class_name = Class_Utils::generate_proxy_class_name($class->get_name(), $this->proxy_namespace);
        $parts = explode('\\', strrev($proxy_class_name), 2);
        return strrev($parts[0]);
    }
    /**
     * Generates the proxy namespace.
     */
    private function generate_namespace(Class_Metadata $class): string
    {
        $proxy_class_name = Class_Utils::generate_proxy_class_name($class->get_name(), $this->proxy_namespace);
        $parts = explode('\\', strrev($proxy_class_name), 2);
        return strrev($parts[1]);
    }
    /**
     * Enums must have a use statement when used as public property defaults.
     */
    public function generate_enum_use_statements(Class_Metadata $class): string
    {
        if (PHP_VERSION_ID < 80100) {
            return "\n";
        }
        $default_properties = $class->get_reflection_class()->get_default_properties();
        $lazy_loaded_public_properties = $this->get_lazy_loaded_public_properties_names($class);
        $enum_classes = [];
        foreach ($class->get_reflection_class()->get_properties(ReflectionProperty::IS_PUBLIC) as $property) {
            $name = $property->get_name();
            if (!in_array($name, $lazy_loaded_public_properties, true)) {
                continue;
            }
            if (array_key_exists($name, $default_properties) && $default_properties[$name] instanceof Backed_Enum) {
                $enum_class_name_parts = explode('\\', get_class($default_properties[$name]));
                $enum_classes[] = $enum_class_name_parts[0];
            }
        }
        return implode("\n", array_map(static function (string $class_name): string {
            return 'use ' . $class_name . ';';
        }, array_unique($enum_classes))) . "\n";
    }
    /**
     * Generates the original class name.
     */
    private function generate_class_name(Class_Metadata $class): string
    {
        return ltrim($class->get_name(), '\\');
    }
    /**
     * Generates the array representation of lazy loaded public properties and their default values.
     */
    private function generate_lazy_properties_names(Class_Metadata $class): string
    {
        $lazy_public_properties = $this->get_lazy_loaded_public_properties_names($class);
        $values = [];
        foreach ($lazy_public_properties as $name) {
            $values[$name] = null;
        }
        return var_export($values, true);
    }
    /**
     * Generates the array representation of lazy loaded public properties names.
     */
    private function generate_lazy_properties_defaults(Class_Metadata $class): string
    {
        return var_export($this->get_lazy_loaded_public_properties($class), true);
    }
    /**
     * Generates the constructor code (un-setting public lazy loaded properties, setting identifier field values).
     */
    private function generate_constructor_impl(Class_Metadata $class): string
    {
        $constructor_impl = <<<'EOT'
            public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
            {
        
        EOT;
        $to_unset = array_map(static function (string $name): string {
            return '$this->' . $name;
        }, $this->get_lazy_loaded_public_properties_names($class));
        return $constructor_impl . ($to_unset === [] ? '' : '        unset(' . implode(', ', $to_unset) . ");\n") . <<<'EOT'
        
                $this->__initializer__ = $initializer;
                $this->__cloner__      = $cloner;
            }
        EOT;
    }
    /**
     * Generates the magic getter invoked when lazy loaded public properties are requested.
     */
    private function generate_magic_get(Class_Metadata $class): string
    {
        $lazy_public_properties = $this->get_lazy_loaded_public_properties_names($class);
        $reflection_class = $class->get_reflection_class();
        $has_parent_get = false;
        $return_reference = '';
        $inherit_doc = '';
        $name = '$name';
        $parameters_string = '$name';
        $return_type_hint = null;
        if ($reflection_class->has_method('__get')) {
            $has_parent_get = true;
            $inherit_doc = '{@inheritDoc}';
            $method_reflection = $reflection_class->get_method('__get');
            if ($method_reflection->returns_reference()) {
                $return_reference = '& ';
            }
            $method_parameters = $method_reflection->get_parameters();
            $name = '$' . $method_parameters[0]->get_name();
            $parameters_string = $this->build_parameters_string($method_reflection->get_parameters(), ['name']);
            $return_type_hint = $this->get_method_return_type($method_reflection);
        }
        if (empty($lazy_public_properties) && !$has_parent_get) {
            return '';
        }
        $magic_get = <<<EOT
            /**
             * {$inherit_doc}
             * @param string \$name
             */
            public function {$return_reference}__get({$parameters_string}){$return_type_hint}
            {
        
        EOT;
        if (!empty($lazy_public_properties)) {
            $magic_get .= <<<'EOT'
                    if (\array_key_exists($name, self::$lazyPropertiesNames)) {
                        $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
            EOT;
            if ($return_type_hint === ': void') {
                $magic_get .= "\n            return;";
            } else {
                $magic_get .= "\n            return \$this->\$name;";
            }
            $magic_get .= <<<'EOT'
            
                    }
            
            
            EOT;
        }
        if ($has_parent_get) {
            $magic_get .= <<<'EOT'
                    $this->__initializer__ && $this->__initializer__->__invoke($this, '__get', [$name]);
            EOT;
            if ($return_type_hint === ': void') {
                $magic_get .= <<<'EOT'
                
                        parent::__get($name);
                        return;
                EOT;
            } elseif ($return_type_hint === ': never') {
                $magic_get .= <<<'EOT'
                
                        parent::__get($name);
                EOT;
            } else {
                $magic_get .= <<<'EOT'
                
                        return parent::__get($name);
                EOT;
            }
        } else {
            $magic_get .= sprintf(<<<EOT
                    trigger_error(sprintf('Undefined property: %%s::\$%%s', __CLASS__, %s), E_USER_NOTICE);
            
            EOT, $name);
        }
        return $magic_get . "\n    }";
    }
    /**
     * Generates the magic setter (currently unused).
     */
    private function generate_magic_set(Class_Metadata $class): string
    {
        $lazy_public_properties = $this->get_lazy_loaded_public_properties_names($class);
        $reflection_class = $class->get_reflection_class();
        $has_parent_set = false;
        $inherit_doc = '';
        $parameters_string = '$name, $value';
        $return_type_hint = null;
        if ($reflection_class->has_method('__set')) {
            $has_parent_set = true;
            $inherit_doc = '{@inheritDoc}';
            $method_reflection = $reflection_class->get_method('__set');
            $parameters_string = $this->build_parameters_string($method_reflection->get_parameters(), ['name', 'value']);
            $return_type_hint = $this->get_method_return_type($method_reflection);
        }
        if (empty($lazy_public_properties) && !$has_parent_set) {
            return '';
        }
        $magic_set = <<<EOT
            /**
             * {$inherit_doc}
             * @param string \$name
             * @param mixed  \$value
             */
            public function __set({$parameters_string}){$return_type_hint}
            {
        
        EOT;
        if (!empty($lazy_public_properties)) {
            $magic_set .= <<<'EOT'
                    if (\array_key_exists($name, self::$lazyPropertiesNames)) {
                        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);
            
                        $this->$name = $value;
            
                        return;
                    }
            
            
            EOT;
        }
        if ($has_parent_set) {
            $magic_set .= <<<'EOT'
                    $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', [$name, $value]);
            EOT;
            if ($return_type_hint === ': void') {
                $magic_set .= <<<'EOT'
                
                        parent::__set($name, $value);
                        return;
                EOT;
            } elseif ($return_type_hint === ': never') {
                $magic_set .= <<<'EOT'
                
                        parent::__set($name, $value);
                EOT;
            } else {
                $magic_set .= <<<'EOT'
                
                        return parent::__set($name, $value);
                EOT;
            }
        } else {
            $magic_set .= '        $this->$name = $value;';
        }
        return $magic_set . "\n    }";
    }
    /**
     * Generates the magic issetter invoked when lazy loaded public properties are checked against isset().
     */
    private function generate_magic_isset(Class_Metadata $class): string
    {
        $lazy_public_properties = $this->get_lazy_loaded_public_properties_names($class);
        $has_parent_isset = $class->get_reflection_class()->has_method('__isset');
        $parameters_string = '$name';
        $return_type_hint = null;
        if ($has_parent_isset) {
            $method_reflection = $class->get_reflection_class()->get_method('__isset');
            $parameters_string = $this->build_parameters_string($method_reflection->get_parameters(), ['name']);
            $return_type_hint = $this->get_method_return_type($method_reflection);
        }
        if (empty($lazy_public_properties) && !$has_parent_isset) {
            return '';
        }
        $inherit_doc = $has_parent_isset ? '{@inheritDoc}' : '';
        $magic_isset = <<<EOT
            /**
             * {$inherit_doc}
             * @param  string \$name
             * @return boolean
             */
            public function __isset({$parameters_string}){$return_type_hint}
            {
        
        EOT;
        if (!empty($lazy_public_properties)) {
            $magic_isset .= <<<'EOT'
                    if (\array_key_exists($name, self::$lazyPropertiesNames)) {
                        $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);
            
                        return isset($this->$name);
                    }
            
            
            EOT;
        }
        if ($has_parent_isset) {
            $magic_isset .= <<<'EOT'
                    $this->__initializer__ && $this->__initializer__->__invoke($this, '__isset', [$name]);
            
                    return parent::__isset($name);
            EOT;
        } else {
            $magic_isset .= '        return false;';
        }
        return $magic_isset . "\n    }";
    }
    /**
     * Generates implementation for the `__sleep` method of proxies.
     */
    private function generate_sleep_impl(Class_Metadata $class): string
    {
        $reflection_class = $class->get_reflection_class();
        $has_parent_sleep = $reflection_class->has_method('__sleep');
        $inherit_doc = $has_parent_sleep ? '{@inheritDoc}' : '';
        $return_type_hint = $has_parent_sleep ? $this->get_method_return_type($reflection_class->get_method('__sleep')) : '';
        $sleep_impl = <<<EOT
            /**
             * {$inherit_doc}
             * @return array
             */
            public function __sleep(){$return_type_hint}
            {
        
        EOT;
        if ($has_parent_sleep) {
            return $sleep_impl . <<<'EOT'
                    $properties = array_merge(['__isInitialized__'], parent::__sleep());
            
                    if ($this->__isInitialized__) {
                        $properties = array_diff($properties, array_keys(self::$lazyPropertiesNames));
                    }
            
                    return $properties;
                }
            EOT;
        }
        $all_properties = ['__isInitialized__'];
        foreach ($class->get_reflection_class()->get_properties() as $prop) {
            assert($prop instanceof ReflectionProperty);
            if ($prop->is_static()) {
                continue;
            }
            $all_properties[] = $prop->is_private() ? "\x00" . $prop->get_declaring_class()->get_name() . "\x00" . $prop->get_name() : $prop->get_name();
        }
        $lazy_public_properties = $this->get_lazy_loaded_public_properties_names($class);
        $protected_properties = array_diff($all_properties, $lazy_public_properties);
        foreach ($all_properties as &$property) {
            $property = var_export($property, true);
        }
        foreach ($protected_properties as &$property) {
            $property = var_export($property, true);
        }
        $all_properties = implode(', ', $all_properties);
        $protected_properties = implode(', ', $protected_properties);
        return $sleep_impl . <<<EOT
                if (\$this->__isInitialized__) {
                    return [{$all_properties}];
                }
        
                return [{$protected_properties}];
            }
        EOT;
    }
    /**
     * Generates implementation for the `__wakeup` method of proxies.
     */
    private function generate_wakeup_impl(Class_Metadata $class): string
    {
        $reflection_class = $class->get_reflection_class();
        $has_parent_wakeup = $reflection_class->has_method('__wakeup');
        $unset_public_properties = [];
        foreach ($this->get_lazy_loaded_public_properties_names($class) as $lazy_public_property) {
            $unset_public_properties[] = '$this->' . $lazy_public_property;
        }
        $short_name = $this->generate_proxy_short_class_name($class);
        $inherit_doc = $has_parent_wakeup ? '{@inheritDoc}' : '';
        $return_type_hint = $has_parent_wakeup ? $this->get_method_return_type($reflection_class->get_method('__wakeup')) : '';
        $wakeup_impl = <<<EOT
            /**
             * {$inherit_doc}
             */
            public function __wakeup(){$return_type_hint}
            {
                if ( ! \$this->__isInitialized__) {
                    \$this->__initializer__ = function ({$short_name} \$proxy) {
                        \$proxy->__setInitializer(null);
                        \$proxy->__setCloner(null);
        
                        \$existingProperties = get_object_vars(\$proxy);
        
                        foreach (\$proxy::\$lazyPropertiesDefaults as \$property => \$defaultValue) {
                            if ( ! array_key_exists(\$property, \$existingProperties)) {
                                \$proxy->\$property = \$defaultValue;
                            }
                        }
                    };
        
        EOT;
        if (!empty($unset_public_properties)) {
            $wakeup_impl .= "\n            unset(" . implode(', ', $unset_public_properties) . ');';
        }
        $wakeup_impl .= "\n        }";
        if ($has_parent_wakeup) {
            $wakeup_impl .= "\n        parent::__wakeup();";
        }
        return $wakeup_impl . "\n    }";
    }
    /**
     * Generates implementation for the `__clone` method of proxies.
     */
    private function generate_clone_impl(Class_Metadata $class): string
    {
        $reflection_class = $class->get_reflection_class();
        $has_parent_clone = $reflection_class->has_method('__clone');
        $return_type_hint = $has_parent_clone ? $this->get_method_return_type($reflection_class->get_method('__clone')) : '';
        $inherit_doc = $has_parent_clone ? '{@inheritDoc}' : '';
        $call_parent_clone = $has_parent_clone ? "\n        parent::__clone();\n" : '';
        return <<<EOT
            /**
             * {$inherit_doc}
             */
            public function __clone(){$return_type_hint}
            {
                \$this->__cloner__ && \$this->__cloner__->__invoke(\$this, '__clone', []);
        {$call_parent_clone}    }
        EOT;
    }
    /**
     * Generates decorated methods by picking those available in the parent class.
     */
    private function generate_methods(Class_Metadata $class): string
    {
        $methods = '';
        $method_names = [];
        $reflection_methods = $class->get_reflection_class()->get_methods(ReflectionMethod::IS_PUBLIC);
        $skipped_methods = ['__sleep' => true, '__clone' => true, '__wakeup' => true, '__get' => true, '__set' => true, '__isset' => true];
        foreach ($reflection_methods as $method) {
            $name = $method->get_name();
            if ($method->is_constructor()) {
                continue;
            }
            if (isset($skipped_methods[strtolower($name)])) {
                continue;
            }
            if (isset($method_names[$name])) {
                continue;
            }
            if ($method->is_final()) {
                continue;
            }
            if ($method->is_static()) {
                continue;
            }
            if (!$method->is_public()) {
                continue;
            }
            $method_names[$name] = true;
            $methods .= "\n    /**\n" . "     * {@inheritDoc}\n" . "     */\n" . '    public function ';
            if ($method->returns_reference()) {
                $methods .= '&';
            }
            $methods .= $name . '(' . $this->build_parameters_string($method->get_parameters()) . ')';
            $methods .= $this->get_method_return_type($method);
            $methods .= "\n" . '    {' . "\n";
            if ($this->is_short_identifier_getter($method, $class)) {
                $identifier = lcfirst(substr($name, 3));
                $field_type = $class->get_type_of_field($identifier);
                $cast = in_array($field_type, ['integer', 'smallint'], true) ? '(int) ' : '';
                $methods .= '        if ($this->__isInitialized__ === false) {' . "\n";
                $methods .= '            ';
                $methods .= $this->should_proxied_method_return($method) ? 'return ' : '';
                $methods .= $cast . ' parent::' . $method->get_name() . "();\n";
                $methods .= '        }' . "\n\n";
            }
            $invoke_params_string = implode(', ', $this->get_parameter_names_for_invoke($method->get_parameters()));
            $call_params_string = implode(', ', $this->get_parameter_names_for_parent_call($method->get_parameters()));
            $methods .= "\n        \$this->__initializer__ " . '&& $this->__initializer__->__invoke($this, ' . var_export($name, true) . ', [' . $invoke_params_string . ']);' . "\n\n        " . ($this->should_proxied_method_return($method) ? 'return ' : '') . 'parent::' . $name . '(' . $call_params_string . ');' . "\n" . '    }' . "\n";
        }
        return $methods;
    }
    /**
     * Generates the Proxy file name.
     *
     * @param string $className
     * @param string $baseDirectory Optional base directory for proxy file name generation.
     *                              If not specified, the directory configured on the Configuration of the
     *                              EntityManager will be used by this factory.
     * @psalm-param class-string $className
     */
    public function get_proxy_file_name($class_name, $base_directory = null): string
    {
        $base_directory = $base_directory ?: $this->proxy_directory;
        return rtrim($base_directory, DIRECTORY_SEPARATOR) . DIRECTORY_SEPARATOR . Proxy::MARKER . str_replace('\\', '', $class_name) . '.php';
    }
    /**
     * Checks if the method is a short identifier getter.
     *
     * What does this mean? For proxy objects the identifier is already known,
     * however accessing the getter for this identifier usually triggers the
     * lazy loading, leading to a query that may not be necessary if only the
     * ID is interesting for the userland code (for example in views that
     * generate links to the entity, but do not display anything else).
     *
     * @param ReflectionMethod $method
     */
    private function is_short_identifier_getter($method, Class_Metadata $class): bool
    {
        $identifier = lcfirst(substr($method->get_name(), 3));
        $start_line = $method->get_start_line();
        $end_line = $method->get_end_line();
        $cheap_check = $method->get_number_of_parameters() === 0 && substr($method->get_name(), 0, 3) === 'get' && in_array($identifier, $class->get_identifier(), true) && $class->has_field($identifier) && $end_line - $start_line <= 4;
        if ($cheap_check) {
            $code = file($method->get_file_name());
            $code = trim(implode(' ', array_slice($code, $start_line - 1, $end_line - $start_line + 1)));
            $pattern = sprintf(self::PATTERN_MATCH_ID_METHOD, $method->get_name(), $identifier);
            if (preg_match($pattern, $code)) {
                return true;
            }
        }
        return false;
    }
    /**
     * Generates the list of public properties to be lazy loaded.
     *
     * @return array<int, string>
     */
    private function get_lazy_loaded_public_properties_names(Class_Metadata $class): array
    {
        $properties = [];
        foreach ($class->get_reflection_class()->get_properties(ReflectionProperty::IS_PUBLIC) as $property) {
            $name = $property->get_name();
            if (!$class->has_field($name) && !$class->has_association($name)) {
                continue;
            }
            if ($class->is_identifier($name)) {
                continue;
            }
            $properties[] = $name;
        }
        return $properties;
    }
    /**
     * Generates the list of default values of public properties.
     *
     * @return mixed[]
     */
    private function get_lazy_loaded_public_properties(Class_Metadata $class): array
    {
        $default_properties = $class->get_reflection_class()->get_default_properties();
        $lazy_loaded_public_properties = $this->get_lazy_loaded_public_properties_names($class);
        $default_values = [];
        foreach ($class->get_reflection_class()->get_properties(ReflectionProperty::IS_PUBLIC) as $property) {
            $name = $property->get_name();
            if (!in_array($name, $lazy_loaded_public_properties, true)) {
                continue;
            }
            if (array_key_exists($name, $default_properties)) {
                $default_values[$name] = $default_properties[$name];
            } elseif (method_exists($property, 'getType')) {
                $property_type = $property->get_type();
                if ($property_type !== null && $property_type->allows_null()) {
                    $default_values[$name] = null;
                }
            }
        }
        return $default_values;
    }
    /**
     * @param ReflectionParameter[] $parameters
     * @param string[]              $renameParameters
     */
    private function build_parameters_string(array $parameters, array $rename_parameters = []): string
    {
        $parameter_definitions = [];
        $i = -1;
        foreach ($parameters as $param) {
            assert($param instanceof ReflectionParameter);
            $i++;
            $parameter_definition = '';
            $parameter_type = $this->get_parameter_type($param);
            if ($parameter_type !== null) {
                $parameter_definition .= $parameter_type . ' ';
            }
            if ($param->is_passed_by_reference()) {
                $parameter_definition .= '&';
            }
            if ($param->is_variadic()) {
                $parameter_definition .= '...';
            }
            $parameter_definition .= '$' . ($rename_parameters ? $rename_parameters[$i] : $param->get_name());
            $parameter_definition .= $this->get_parameter_default_value($param);
            $parameter_definitions[] = $parameter_definition;
        }
        return implode(', ', $parameter_definitions);
    }
    /** @return string|null */
    private function get_parameter_type(ReflectionParameter $parameter)
    {
        if (!$parameter->has_type()) {
            return null;
        }
        $declaring_function = $parameter->get_declaring_function();
        assert($declaring_function instanceof ReflectionMethod);
        return $this->format_type($parameter->get_type(), $declaring_function, $parameter);
    }
    private function get_parameter_default_value(ReflectionParameter $parameter): string
    {
        if (!$parameter->is_default_value_available()) {
            return '';
        }
        if (PHP_VERSION_ID < 80100 || is_scalar($parameter->get_default_value())) {
            return ' = ' . var_export($parameter->get_default_value(), true);
        }
        $value = rtrim(substr(explode('$' . $parameter->get_name() . ' = ', (string) $parameter, 2)[1], 0, -2));
        if (strpos($value, '\\') !== false || strpos($value, '::') !== false) {
            $value = preg_split("/('(?:[^'\\\\]*+(?:\\\\.)*+)*+')/", $value, -1, PREG_SPLIT_DELIM_CAPTURE);
            foreach ($value as $i => $part) {
                if ($i % 2 === 0) {
                    $value[$i] = preg_replace('/(?<![a-zA-Z0-9_\x7f-\xff\\\\])[a-zA-Z0-9_\x7f-\xff]++(?:\\\\[a-zA-Z0-9_\x7f-\xff]++|::)++/', '\\\\\\0', $part);
                }
            }
            $value = implode('', $value);
        }
        return ' = ' . $value;
    }
    /**
     * @param ReflectionParameter[] $parameters
     *
     * @return string[]
     */
    private function get_parameter_names_for_invoke(array $parameters): array
    {
        return array_map(static function (ReflectionParameter $parameter): string {
            return '$' . $parameter->get_name();
        }, $parameters);
    }
    /**
     * @param ReflectionParameter[] $parameters
     *
     * @return string[]
     */
    private function get_parameter_names_for_parent_call(array $parameters): array
    {
        return array_map(static function (ReflectionParameter $parameter): string {
            $name = '';
            if ($parameter->is_variadic()) {
                $name .= '...';
            }
            return $name . ('$' . $parameter->get_name());
        }, $parameters);
    }
    private function get_method_return_type(ReflectionMethod $method): string
    {
        if (!$method->has_return_type()) {
            return '';
        }
        return ': ' . $this->format_type($method->get_return_type(), $method);
    }
    /** @return bool */
    private function should_proxied_method_return(ReflectionMethod $method)
    {
        if (!$method->has_return_type()) {
            return true;
        }
        return !in_array(strtolower($this->format_type($method->get_return_type(), $method)), ['void', 'never'], true);
    }
    /** @return string */
    private function format_type(Reflection_Type $type, ReflectionMethod $method, ?ReflectionParameter $parameter = null)
    {
        if ($type instanceof ReflectionUnionType) {
            return implode('|', array_map(function (Reflection_Type $unioned_type) use ($method, $parameter) {
                if ($unioned_type instanceof ReflectionIntersectionType) {
                    return '(' . $this->format_type($unioned_type, $method, $parameter) . ')';
                }
                return $this->format_type($unioned_type, $method, $parameter);
            }, $type->get_types()));
        }
        if ($type instanceof ReflectionIntersectionType) {
            return implode('&', array_map(function (Reflection_Type $intersected_type) use ($method, $parameter) {
                return $this->format_type($intersected_type, $method, $parameter);
            }, $type->get_types()));
        }
        assert($type instanceof ReflectionNamedType);
        $name = $type->get_name();
        $name_lower = strtolower($name);
        if ($name_lower === 'static') {
            $name = 'static';
        }
        if ($name_lower === 'self') {
            $name = $method->get_declaring_class()->get_name();
        }
        if ($name_lower === 'parent') {
            $name = $method->get_declaring_class()->get_parent_class()->get_name();
        }
        if (!$type->is_builtin() && !class_exists($name) && !interface_exists($name) && $name !== 'static') {
            if ($parameter !== null) {
                throw UnexpectedValueException::invalid_parameter_type_hint($method->get_declaring_class()->get_name(), $method->get_name(), $parameter->get_name());
            }
            throw UnexpectedValueException::invalid_return_type_hint($method->get_declaring_class()->get_name(), $method->get_name());
        }
        if (!$type->is_builtin() && $name !== 'static') {
            $name = '\\' . $name;
        }
        if ($type->allows_null() && !in_array($name, ['mixed', 'null'], true)) {
            return '?' . $name;
        }
        return $name;
    }
}